language: java

sudo: false

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./gradlew

install:
  - ./gradlew tasks

script:
  - ./travis-build.sh
